### ISSUE TITLE
Static analysis and Inspection test type vs Automated

### ISSUE THREAD

**Issue by gabrielasd** [muralidn/CAS741-Fall20#46]
Hi @muralidn,
Your VnV Plan looks really good to me, so I have few questions (I'll split then into separate issues)

In page 10 of the VnV Plan, you describe two nonfunctional tests, Divide by-zero check and Negative square root check. These are classified as "Static analysis and Inspection", but couldn't they be automated? when the code checks for a zero division, couldn't an exception be raised? or maybe this don't apply to your code?

**Comment by muralidn** [comment]
Thanks, @gabrielasd .

The static analyzer from Pycharm was not detecting these errors.  I was thinking of either writing unit tests or doing a data/control coupling analysis on the parent function, but ultimately decided on a code inspection because the source code for my application is not going to be large, and inspection may take less effort than automation. 

That said, I am going to keep this ticket open until the unit tests are complete, in case I find some other tool or method for automation.

**Comment by muralidn** [comment]
Since the Drasil generated code was relatively small and modularized, a code inspection proved to be the best method to tackle the issue. Moreover, the physical constraints check of the SRS  ensured that a divide by zero scenario does not occur.
