### ISSUE TITLE
Divide by zero and negative square root

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#52]
For these two test cases, I don't think you are doing by manual inspection. You can verify it by checking the value before the division in your code or by catching an error. You don't need to manually look through the code again, just let the program show an error message would be fine.

**Comment by muralidn** [comment]
Since the Drasil generated code was relatively small and modularized, a code inspection proved to be the best method to tackle the issue. Moreover, the physical constraints check of the SRS  ensured that a divide by zero scenario does not occur.

With the new scope (#55) the negative square root check was no longer an issue for my software.
