### ISSUE TITLE
Compilation errors after disabling comments

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#6]
Hello Dr. Smith,

I was trying to disable comments in the deliverables by setting the ` commentsfalse` flag (line 5) in the file [./docs/Comments.tex](https://github.com/muralidn/CAS741-Fall20/blob/master/docs/Comments.tex)

After setting the flag, during the compilation of the SRS, I encountered the following error message,

```
This is BibTeX, Version 0.99d (MiKTeX 20.6.29)
The top-level auxiliary file: SRS.aux
The style file: plainnat.bst
I found no \citation commands---while reading file SRS.aux
Database file #1: ../../refs/References.bib
(There was 1 error message)
```

There are two citations (lines 202 and 213) in [./docs/SRS/SRS.tex](https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.tex. ) that are part of the template-comments.  Should we clear all references from [./refs/References.bib](https://github.com/muralidn/CAS741-Fall20/blob/master/refs/References.bib) before we disable the comments ?. Is there a way to programmatically enable/disable references as well ?.

Please share your thoughts on this.

**Comment by smiths** [comment]
@muralidn I'm sure that there are clever things you could do to make make more flexible, but the problem only came up because the only citations in the SRS are in comments.  When you complete the document, this will no longer be the case.  I'm sure you will have other citations.  Therefore, my advice is to just not call bibtex on the file when there are no citations.  :smile:

**Comment by muralidn** [comment]
Thank You, Dr. Smith!
